// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./src/view/404/index.vue')['default']
    Chat: typeof import('./src/view/Chat/index.vue')['default']
    DiaLog: typeof import('./src/components/DiaLog/index.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    Footer: typeof import('./src/layout/Footer.vue')['default']
    Home: typeof import('./src/view/Home/index.vue')['default']
    Login: typeof import('./src/view/Login/index.vue')['default']
    MyImg: typeof import('./src/components/ErrorImage/MyImg.vue')['default']
    Register: typeof import('./src/view/Register/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/view/Setting/index.vue')['default']
    Undefined: typeof import('./src/layout/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    WangEditor: typeof import('./src/components/WangEditor/index.vue')['default']
    Websocket: typeof import('./src/view/Websocket/index.vue')['default']
  }
}
